# Copyright (C) 2022-2024 Hulevych Mykhailo
# SPDX-License-Identifier: MIT

if(NOT DEFINED CIDER_VARS_EXPORTED)
cider_export_var(CIDER_VARS_EXPORTED 1)

cider_export_var(CIDER_BINARY_DIR ${CIDER_BINARY_DIR})
cider_export_var(CIDER_CMAKE_DIR ${CIDER_CMAKE_DIR})
cider_export_var(CIDER_INCLUDE_DIR ${CIDER_ROOT_DIR}/src)

#output
cider_export_var(CIDER_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY})
cider_export_var(CIDER_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})
cider_export_var(CIDER_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})
endif()
